import type { Metadata } from 'next'
import "@/app/globals.css"
import 'tailwindcss/tailwind.css'
import axios from 'axios'
import StoreProvider from "@/redux/StoreProvider"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="App">
          <StoreProvider>
          {children}
          </StoreProvider>
        </div>
      </body>
    </html>
  )
}
